// <auto-generated />
namespace TicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class kargoTakip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargoTakip));
        
        string IMigrationMetadata.Id
        {
            get { return "202108120615317_kargoTakip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
